# Generated by Django 6.0.2 on 2026-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turfs/'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
